# Generated by Django 4.2.6 on 2023-10-25 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
